name: Build
on: [push, pull_request]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_DEFAULT_REGION: 'eu-west-1'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: |
          npm ci
          npm run build
          sed 's/dist\///g' frame.html > dist/frame.html
          rm -r dist/src
          rm dist/*.map
      - name: Upload dist to AWS S3
        run: | 
          aws s3 cp ./dist s3://${{ env.AWS_S3_BUCKET }}/web-sdk-client/ --exclude "*.js.map" --recursive --acl public-read

